language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - graphviz
      - doxygen
      - cmake

before_install: 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen  ; fi

script:
  - cmake --version
  - doxygen --version
  - echo "Hello $TRAVIS_OS_NAME"
  - echo "$CXX_COMPILER"
  - $CXX_COMPILER --version
  - env

matrix:
  include:
  - compiler: gcc
    env: CXX_COMPILER=g++-5 CC_COMPILER=gcc-5
    os: linux
    dist: trusty
    sudo: required
  - compiler: clang
    env: CXX_COMPILER=clang++-3.7 CC_COMPILER=clang-3.7
    os: linux
    dist: trusty
    sudo: required
  - compiler: clang
    env: CXX_COMPILER=clang++ CC_COMPILER=clang
    os: osx
    osx_image: xcode8.2
