language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - graphviz
      - doxygen
      - cmake

before_install: 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake    ; fi

script:
  - graphviz --version
  - cmake --version
  - doxygen --version

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2
