language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - graphviz
      - doxygen
      - cmake

before_install: 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen  ; fi

script:
  - cmake --version
  - doxygen --version
  - echo "Hello $TRAVIS_OS_NAME"
  - $CXX --version
  - env

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
    - os: osx
      osx_image: xcode7.2
      compiler: clang
