FROM ubuntu:17.04
MAINTAINER Matthias Schmieder <schmieder.matthias@gmail.com>

COPY ubuntu-17.04_custom.list /etc/apt/sources.list.d/
COPY common_install.sh common_cleanup.sh ubuntu-17.04_install.sh /

RUN bash -x /common_install.sh && \
    bash -x /ubuntu-17.04_install.sh && \
    bash -x /common_cleanup.sh
